version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/course-management
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=course_management
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/course-management
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=course_management
      - SEED_ONLY=true
    entrypoint: ["/bin/sh", "-c"]
    command: ["apk add --no-cache netcat-openbsd && ./wait-for-db.sh mongodb mysql /app/startup.sh"]
    volumes:
      - ./wait-for-db.sh:/app/wait-for-db.sh
    restart: "no"

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mysql:
    image: mariadb:10.5.8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=course_management
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mongodb_data:
  mysql_data: 